spring.application.name=reviews-service
# === Mongo ===
# Usa variables de entorno del .env
spring.data.mongodb.uri=${DB_URI}
spring.data.mongodb.database=${DB_NAME}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.auto-index-creation=true

# === Server & Timezone ===
server.port=8090
spring.jackson.time-zone=America/Bogota