spring.application.name=restaurants-service
# MongoDB Configuration
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${DB_URI}
spring.data.mongodb.database=${DB_NAME}
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8081
spring.jackson.time-zone=America/Bogota
spring.data.mongodb.ssl.enabled=true